from app import app, db, Word

# 追加する単語のリストを作成
words = [
    {"word": "abandon", "meaning": "To give up completely", "pronunciation": "əˈbændən", "example_sentence": "He had to abandon his car due to the snow."},
    {"word": "abbreviate", "meaning": "To shorten", "pronunciation": "əˈbriːvieɪt", "example_sentence": "You can abbreviate 'Saint' as 'St.'."},
    {"word": "ability", "meaning": "The power or skill to do something", "pronunciation": "əˈbɪlɪti", "example_sentence": "He has the ability to solve complex problems."},
    {"word": "abnormal", "meaning": "Not usual, not typical, strange", "pronunciation": "æbˈnɔːrməl", "example_sentence": "The weather this year has been very abnormal."},
    {"word": "abolish", "meaning": "To put an end to", "pronunciation": "əˈbɒlɪʃ", "example_sentence": "Slavery was abolished in the 19th century."},
    {"word": "abrupt", "meaning": "Sudden and unexpected", "pronunciation": "əˈbrʌpt", "example_sentence": "The meeting came to an abrupt end."},
    {"word": "absolute", "meaning": "Complete; totally unlimited; certain", "pronunciation": "ˈæbsəluːt", "example_sentence": "She had absolute faith in her decision."},
    {"word": "absorb", "meaning": "To take in or soak up", "pronunciation": "əbˈzɔːrb", "example_sentence": "Plants absorb water through their roots."},
    {"word": "abstract", "meaning": "Existing in thought or as an idea but not having a physical or concrete existence", "pronunciation": "ˈæbstrækt", "example_sentence": "Abstract ideas such as love or beauty can be hard to define."},
    {"word": "abundant", "meaning": "More than enough; plentiful", "pronunciation": "əˈbʌndənt", "example_sentence": "The region is abundant in natural resources."},
    {"word": "access", "meaning": "A means to obtain entry or a means of approach", "pronunciation": "ˈækses", "example_sentence": "He gained access to the secret files."},
    {"word": "accommodate", "meaning": "To make fit, adjust to", "pronunciation": "əˈkɒmədeɪt", "example_sentence": "The hotel can accommodate 200 guests."},
    {"word": "accompany", "meaning": "To go along with; to be together", "pronunciation": "əˈkʌmpəni", "example_sentence": "Children under 12 must be accompanied by an adult."},
    {"word": "accomplish", "meaning": "To do, make happen, succeed in, carry through", "pronunciation": "əˈkʌmplɪʃ", "example_sentence": "She accomplished her goal of graduating from college."},
    {"word": "accumulate", "meaning": "To gather or collect", "pronunciation": "əˈkjuːmjəleɪt", "example_sentence": "Dust had accumulated on the shelves."},
    {"word": "accurate", "meaning": "Correct in all details; exact.", "pronunciation": "ˈækjərət", "example_sentence": "The information was accurate and reliable."},
    {"word": "accuse", "meaning": "To say that someone has done something wrong", "pronunciation": "əˈkjuːz", "example_sentence": "She was accused of stealing the money."},
    {"word": "achieve", "meaning": "To accomplish", "pronunciation": "əˈtʃiːv", "example_sentence": "He achieved his dream of becoming a doctor."},
    {"word": "acknowledge", "meaning": "To recognize; admit", "pronunciation": "əkˈnɒlɪdʒ", "example_sentence": "She acknowledged her mistake."},
    {"word": "acquire", "meaning": "To get or obtain", "pronunciation": "əˈkwaɪər", "example_sentence": "He acquired a new skill while working there."},
    {"word": "adapt", "meaning": "To adjust or change to suit conditions", "pronunciation": "əˈdæpt", "example_sentence": "Animals adapt to their environment in various ways."},
    {"word": "adequate", "meaning": "Enough; sufficient", "pronunciation": "ˈædɪkwət", "example_sentence": "The food was adequate for all the guests."},
    {"word": "adjacent", "meaning": "Next to; nearby", "pronunciation": "əˈdʒeɪsnt", "example_sentence": "The school is adjacent to the park."},
    {"word": "adjust", "meaning": "To change or alter in order to fit or conform", "pronunciation": "əˈdʒʌst", "example_sentence": "He adjusted the seat to his height."},
    {"word": "administer", "meaning": "To manage or direct", "pronunciation": "ədˈmɪnɪstər", "example_sentence": "The nurse will administer the medication."},
    {"word": "admire", "meaning": "To respect or think well of someone or something", "pronunciation": "ədˈmaɪər", "example_sentence": "I admire her for her dedication."},
    {"word": "admission", "meaning": "Confession; entrance", "pronunciation": "ədˈmɪʃən", "example_sentence": "She applied for admission to the university."},
    {"word": "adopt", "meaning": "To take into your family", "pronunciation": "əˈdɒpt", "example_sentence": "They decided to adopt a child."},
    {"word": "advance", "meaning": "To move forward", "pronunciation": "ədˈvɑːns", "example_sentence": "The army advanced towards the enemy."},
    {"word": "advantage", "meaning": "A condition or circumstance that puts one in a favorable or superior position", "pronunciation": "ədˈvɑːntɪdʒ", "example_sentence": "He had an advantage over his opponents."},
    {"word": "adventure", "meaning": "An unusual or exciting experience", "pronunciation": "ədˈventʃər", "example_sentence": "They went on an adventure in the mountains."},
    {"word": "adverse", "meaning": "Not helpful; harmful", "pronunciation": "ədˈvɜːs", "example_sentence": "He faced adverse conditions during his journey."},
    {"word": "advise", "meaning": "To recommend", "pronunciation": "ədˈvaɪz", "example_sentence": "She advised him to see a doctor."},
    {"word": "advocate", "meaning": "To speak in favor of", "pronunciation": "ˈædvəkeɪt", "example_sentence": "She is an advocate for women's rights."},
    {"word": "affect", "meaning": "To influence", "pronunciation": "əˈfekt", "example_sentence": "The weather can affect your mood."},
    {"word": "affection", "meaning": "A feeling of love or liking; tender feeling", "pronunciation": "əˈfekʃn", "example_sentence": "She showed great affection for her dog."},
    {"word": "afford", "meaning": "To be able to pay for", "pronunciation": "əˈfɔːrd", "example_sentence": "I can't afford to buy a new car."},
    {"word": "aggregate", "meaning": "Total", "pronunciation": "ˈæɡrɪɡət", "example_sentence": "The aggregate score was 5-2."},
    {"word": "aggressive", "meaning": "Hostile and unfriendly in the way one expresses oneself", "pronunciation": "əˈɡresɪv", "example_sentence": "He has an aggressive personality."},
    {"word": "allocate", "meaning": "To distribute", "pronunciation": "ˈæləkeɪt", "example_sentence": "The funds were allocated for the project."},
    {"word": "alternative", "meaning": "One of a number of things from which only one can be chosen", "pronunciation": "ɔːlˈtɜːrnətɪv", "example_sentence": "We have no alternative but to cancel the event."},
    {"word": "ambiguous", "meaning": "Unclear", "pronunciation": "æmˈbɪɡjuəs", "example_sentence": "The instructions were ambiguous and confusing."},
    {"word": "ambition", "meaning": "A strong drive for success", "pronunciation": "æmˈbɪʃn", "example_sentence": "Her ambition is to become a doctor."},
    {"word": "analyze", "meaning": "To examine", "pronunciation": "ˈænəlaɪz", "example_sentence": "Scientists analyze data to make discoveries."},
    {"word": "ancestor", "meaning": "A person from whom one is descended", "pronunciation": "ˈænsestər", "example_sentence": "Her ancestors came from Ireland."},
    {"word": "ancient", "meaning": "Very old", "pronunciation": "ˈeɪnʃənt", "example_sentence": "They discovered ancient ruins in the forest."},
    {"word": "anniversary", "meaning": "The date on which an event occurs every year", "pronunciation": "ˌænɪˈvɜːrsəri", "example_sentence": "They celebrated their wedding anniversary."},
    {"word": "anticipate", "meaning": "To expect beforehand", "pronunciation": "ænˈtɪsɪpeɪt", "example_sentence": "We anticipate a good harvest this year."},
    {"word": "anxiety", "meaning": "The condition of feeling uneasy or worried about what may happen", "pronunciation": "æŋˈzaɪəti", "example_sentence": "She suffers from anxiety about her exams."},
    {"word": "apparent", "meaning": "Obvious", "pronunciation": "əˈpærənt", "example_sentence": "It was apparent that he was lying."},
    {"word": "appeal", "meaning": "To make a request", "pronunciation": "əˈpiːl", "example_sentence": "He made an appeal for donations."},
    {"word": "appreciate", "meaning": "To be thankful for", "pronunciation": "əˈpriːʃieɪt", "example_sentence": "I appreciate your help."},
    {"word": "approach", "meaning": "To come near", "pronunciation": "əˈproʊtʃ", "example_sentence": "The car slowly approached the intersection."},
    {"word": "appropriate", "meaning": "Suitable", "pronunciation": "əˈproʊpriət", "example_sentence": "The movie is appropriate for children."},
    {"word": "approximate", "meaning": "Not exact, but close enough to be reasonably correct", "pronunciation": "əˈprɑːksɪmət", "example_sentence": "The approximate cost is $100."},
    {"word": "arbitrary", "meaning": "Based on random choice or personal whim", "pronunciation": "ˈɑːrbɪtreri", "example_sentence": "The decision was completely arbitrary."},
    {"word": "architecture", "meaning": "The art or practice of designing and constructing buildings", "pronunciation": "ˈɑːrkɪtektʃər", "example_sentence": "He studied architecture in college."},
    {"word": "arrange", "meaning": "To put in a certain order", "pronunciation": "əˈreɪndʒ", "example_sentence": "She arranged the flowers in a vase."},
    {"word": "artificial", "meaning": "Made by humans", "pronunciation": "ˌɑːrtɪˈfɪʃl", "example_sentence": "The flowers were made of artificial material."},
    {"word": "ascertain", "meaning": "To find out", "pronunciation": "ˌæsərˈteɪn", "example_sentence": "We need to ascertain what happened."},
    {"word": "aspect", "meaning": "A part that can be considered or viewed", "pronunciation": "ˈæspekt", "example_sentence": "The financial aspect of the project is important."},
    {"word": "assemble", "meaning": "To put together", "pronunciation": "əˈsembl", "example_sentence": "They assembled the new furniture."},
    {"word": "assess", "meaning": "To evaluate", "pronunciation": "əˈses", "example_sentence": "The teacher will assess your performance."},
    {"word": "assign", "meaning": "To give someone a particular job or task", "pronunciation": "əˈsaɪn", "example_sentence": "The manager assigned the task to her team."},
    {"word": "assist", "meaning": "To help", "pronunciation": "əˈsɪst", "example_sentence": "He assisted her with the project."},
    {"word": "assume", "meaning": "To take for granted or without proof", "pronunciation": "əˈsuːm", "example_sentence": "I assume you have completed the work."},
    {"word": "assure", "meaning": "To guarantee", "pronunciation": "əˈʃʊr", "example_sentence": "He assured her that everything would be fine."},
    {"word": "astonish", "meaning": "To surprise or amaze", "pronunciation": "əˈstɒnɪʃ", "example_sentence": "The magician's tricks astonished the audience."},
    {"word": "atmosphere", "meaning": "The envelope of gases surrounding the earth or another planet", "pronunciation": "ˈætməsfɪr", "example_sentence": "The atmosphere of the planet is mostly nitrogen."},
    {"word": "attach", "meaning": "To connect", "pronunciation": "əˈtætʃ", "example_sentence": "Please attach the document to your email."},
    {"word": "attain", "meaning": "To achieve", "pronunciation": "əˈteɪn", "example_sentence": "She attained her goal of becoming a lawyer."},
    {"word": "attempt", "meaning": "To try", "pronunciation": "əˈtempt", "example_sentence": "He attempted to climb the mountain."},
    {"word": "attend", "meaning": "To go to or be present at", "pronunciation": "əˈtend", "example_sentence": "She attends classes regularly."},
    {"word": "attention", "meaning": "Focusing awareness on a narrowed range of stimuli or events", "pronunciation": "əˈtenʃn", "example_sentence": "He paid close attention to the instructions."},
    {"word": "attitude", "meaning": "A person's consistently favorable or unfavorable evaluations, feelings, and tendencies toward an object or idea", "pronunciation": "ˈætɪtuːd", "example_sentence": "She has a positive attitude towards life."},
    {"word": "attribute", "meaning": "A quality or characteristic belonging to or associated with someone or something", "pronunciation": "əˈtrɪbjuːt", "example_sentence": "Patience is an important attribute for a teacher."},
    {"word": "audience", "meaning": "The listener, viewer, or reader of a text", "pronunciation": "ˈɔːdiəns", "example_sentence": "The audience applauded the performance."},
    {"word": "author", "meaning": "A writer of a book, article, or report", "pronunciation": "ˈɔːθər", "example_sentence": "She is the author of several novels."},
    {"word": "authority", "meaning": "The power or right to give orders, make decisions, and enforce obedience", "pronunciation": "əˈθɔːrəti", "example_sentence": "He has the authority to make decisions."},
    {"word": "available", "meaning": "Ready for use, at hand", "pronunciation": "əˈveɪləbl", "example_sentence": "The book is available in the library."},
    {"word": "average", "meaning": "Not special or unusual; ordinary", "pronunciation": "ˈævərɪdʒ", "example_sentence": "She is of average height."},
    {"word": "avoid", "meaning": "To stay away from", "pronunciation": "əˈvɔɪd", "example_sentence": "He tried to avoid the traffic jam."},
    {"word": "aware", "meaning": "Knowing about something", "pronunciation": "əˈwer", "example_sentence": "She is aware of the risks involved."},
    {"word": "balance", "meaning": "A condition in which different elements are equal or in the correct proportions", "pronunciation": "ˈbæləns", "example_sentence": "Work-life balance is important."},
    {"word": "barrier", "meaning": "Something that blocks the way; an obstacle", "pronunciation": "ˈbæriər", "example_sentence": "Language barriers can hinder communication."},
    {"word": "benefit", "meaning": "To gain or receive good results from something", "pronunciation": "ˈbenɪfɪt", "example_sentence": "Exercise has many health benefits."},
    {"word": "bias", "meaning": "Prejudice or predisposition toward one side of a subject or issue", "pronunciation": "ˈbaɪəs", "example_sentence": "The report showed a clear bias towards one side."},
    {"word": "bizarre", "meaning": "Strikingly out of the ordinary; peculiar", "pronunciation": "bɪˈzɑːr", "example_sentence": "The story was too bizarre to be true."},
    {"word": "blend", "meaning": "To mix together different elements", "pronunciation": "blend", "example_sentence": "He blended the ingredients to make a smoothie."},
    {"word": "block", "meaning": "The section of a street between two other streets", "pronunciation": "blɒk", "example_sentence": "The children played outside on the block."},
    {"word": "brief", "meaning": "Short", "pronunciation": "briːf", "example_sentence": "She gave a brief introduction to the topic."},
    {"word": "broadcast", "meaning": "To transmit a program or some information by radio or television", "pronunciation": "ˈbrɔːdkæst", "example_sentence": "The news was broadcast live."},
    {"word": "budget", "meaning": "A plan for making and spending money", "pronunciation": "ˈbʌdʒɪt", "example_sentence": "They planned a budget for the project."},
    {"word": "burden", "meaning": "A load, especially a heavy one", "pronunciation": "ˈbɜːrdn", "example_sentence": "She carried a heavy burden on her shoulders."},
    {"word": "calculate", "meaning": "To work out by using arithmetic", "pronunciation": "ˈkælkjəleɪt", "example_sentence": "He calculated the total cost."},
    {"word": "campaign", "meaning": "A series of actions intended to accomplish a goal", "pronunciation": "kæmˈpeɪn", "example_sentence": "They launched a campaign to raise awareness."},
    {"word": "capacity", "meaning": "The maximum amount that something can contain", "pronunciation": "kəˈpæsəti", "example_sentence": "The stadium was filled to capacity."},
    {"word": "category", "meaning": "A group of people or things having something in common", "pronunciation": "ˈkætəɡɔːri", "example_sentence": "The books were arranged by category."},
    {"word": "caution", "meaning": "Care taken to avoid danger or mistakes", "pronunciation": "ˈkɔːʃn", "example_sentence": "He exercised caution while driving."},
    {"word": "celebrate", "meaning": "To honor something in a special way", "pronunciation": "ˈselɪbreɪt", "example_sentence": "They celebrated her birthday with a party."},
    {"word": "challenge", "meaning": "A demanding or stimulating situation", "pronunciation": "ˈtʃælɪndʒ", "example_sentence": "The project was a significant challenge."},
    {"word": "character", "meaning": "The distinctive qualities that describe how a person thinks, feels, and behaves", "pronunciation": "ˈkærɪktər", "example_sentence": "She has a strong and kind character."},
    {"word": "circumstance", "meaning": "Condition surrounding something; a situation", "pronunciation": "ˈsɜːrkəmstæns", "example_sentence": "The circumstances of the accident are unclear."},
    {"word": "cite", "meaning": "To quote", "pronunciation": "saɪt", "example_sentence": "He cited a famous author in his essay."},
    {"word": "clarify", "meaning": "To make clear or easier to understand", "pronunciation": "ˈklærɪfaɪ", "example_sentence": "She clarified her statement for the audience."}
]


def add_words_to_db():
    with app.app_context():
        for word_data in words:
            word = Word(
                word=word_data['word'],
                meaning=word_data['meaning'],
                pronunciation=word_data.get('pronunciation', ''),
                example_sentence=word_data.get('example_sentence', '')
            )
            db.session.add(word)
        db.session.commit()
        print(f"{len(words)} words added to the database.")

if __name__ == '__main__':
    add_words_to_db()
