"""Add correct_count and total_count to Word model

Revision ID: ea2b7c57b3b8
Revises: 
Create Date: 2024-07-05 12:43:03.008082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2b7c57b3b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_column('total_count')
        batch_op.drop_column('correct_count')

    # ### end Alembic commands ###
