"""Add pronunciation and example_sentence columns to Word

Revision ID: f4d74b5a91dd
Revises: ea2b7c57b3b8
Create Date: 2024-07-05 14:27:08.745168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d74b5a91dd'
down_revision = 'ea2b7c57b3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronunciation', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('example_sentence', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_column('example_sentence')
        batch_op.drop_column('pronunciation')

    # ### end Alembic commands ###
